spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/nation
    username: root  
    password: Mpakakos.13
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update      # options: validate | update | create | create-drop
    show-sql: true           # shows SQL in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  profiles:
    active: dev              # can be 'dev', 'test', 'prod'
server:
  port: 8082
  servlet:
    context-path: /api
# Logging configuration (optional)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
